# 建表语句
create table if not exists medical_insure_data
(
    个人编码                       bigint default 0 not null
        primary key,
    一天去两家医院的天数           int              null,
    就诊的月数                     int              null,
    月就诊天数_MAX                 int              null,
    月就诊天数_AVG                 double           null,
    月就诊医院数_MAX               int              null,
    月就诊医院数_AVG               double           null,
    就诊次数_SUM                   int              null,
    月就诊次数_MAX                 int              null,
    月就诊次数_AVG                 double           null,
    月统筹金额_MAX                 double           null,
    月统筹金额_AVG                 double           null,
    月药品金额_MAX                 double           null,
    月药品金额_AVG                 double           null,
    医院_就诊天数_MAX              int              null,
    医院_就诊天数_AVG              double           null,
    医院_统筹金_MAX                double           null,
    医院_统筹金_AVG                double           null,
    医院_药品_MAX                  double           null,
    医院_药品_AVG                  double           null,
    医院编码_NN                    int              null,
    顺序号_NN                      int              null,
    交易时间DD_NN                  int              null,
    交易时间YYYY_NN                int              null,
    交易时间YYYYMM_NN              int              null,
    住院天数_SUM                   int              null,
    个人账户金额_SUM               double           null,
    统筹支付金额_SUM               double           null,
    ALL_SUM                        double           null,
    可用账户报销金额_SUM           double           null,
    药品费发生金额_SUM             double           null,
    药品费自费金额_SUM             double           null,
    药品费申报金额_SUM             double           null,
    贵重药品发生金额_SUM           double           null,
    中成药费发生金额_SUM           double           null,
    中草药费发生金额_SUM           double           null,
    检查费发生金额_SUM             int              null,
    检查费自费金额_SUM             int              null,
    检查费申报金额_SUM             double           null,
    贵重检查费金额_SUM             int              null,
    治疗费发生金额_SUM             double           null,
    治疗费自费金额_SUM             int              null,
    治疗费申报金额_SUM             double           null,
    手术费发生金额_SUM             int              null,
    手术费自费金额_SUM             int              null,
    手术费申报金额_SUM             int              null,
    床位费发生金额_SUM             int              null,
    床位费申报金额_SUM             int              null,
    医用材料发生金额_SUM           double           null,
    高价材料发生金额_SUM           int              null,
    医用材料费自费金额_SUM         double           null,
    成分输血申报金额_SUM           int              null,
    其它发生金额_SUM               double           null,
    其它申报金额_SUM               int              null,
    一次性医用材料申报金额_SUM     double           null,
    起付线标准金额_MAX             int              null,
    起付标准以上自负比例金额_SUM   double           null,
    医疗救助个人按比例负担金额_SUM int              null,
    最高限额以上金额_SUM           int              null,
    基本统筹基金支付金额_SUM       double           null,
    公务员医疗补助基金支付金额_SUM int              null,
    城乡救助补助金额_SUM           double           null,
    基本个人账户支付_SUM           double           null,
    非账户支付金额_SUM             double           null,
    本次审批金额_SUM               double           null,
    补助审批金额_SUM               double           null,
    医疗救助医院申请_SUM           int              null,
    残疾军人补助_SUM               int              null,
    民政救助补助_SUM               double           null,
    城乡优抚补助_SUM               int              null,
    出院诊断病种名称_NN            int              null,
    出院诊断LENTH_MAX              int              null,
    药品在总金额中的占比           double           null,
    个人支付的药品占比             double           null,
    检查总费用在总金额占比         double           null,
    个人支付检查费用占比           double           null,
    治疗费用在总金额占比           double           null,
    个人支付治疗费用占比           double           null,
    BZ_民政救助                    int              null,
    BZ_城乡优抚                    int              null,
    是否挂号                       int              null,
    RES                            int              null
);

create table if not exists user
(
    id          int unsigned auto_increment comment '用户id 主键'
        primary key,
    username    varchar(20)  not null,
    password    varchar(20)  null,
    name        varchar(10)  null,
    email       varchar(128) null,
    phone       varchar(20)  null,
    user_pic    varchar(128) null,
    department  varchar(20)  null,
    job         varchar(10)  null,
    create_time datetime     null,
    update_time datetime     null
);

delete from medical_insure_data where 1 = 1;